### ISSUE TITLE
Problem with typhoeus (0.2.4)

### ISSUE THREAD

**Issue by burmjohn** [jdpace/the_games_db#2]
Hello,

Is there a specific reason why version 0.2.4 of typhoeus is required?

Getting the error: undefined symbol: curl_multi_init and it seems to be related to versions of typhoeus before 0.4.x on deb boxes.  

https://github.com/typhoeus/typhoeus/issues/117

Thanks!
John

**Comment by jdpace** [comment]
I've loosened the version requirements for dependencies across the board so this should no longer be an issue.
